from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime

class DataProvenance(BaseModel):
    """
    Every derived result must retain its provenance through the analytical pipeline.
    """
    metric: str = Field(..., description="e.g., sst_trend, anomaly")
    value: float
    unit: str
    method: str = Field(..., description="e.g., linear_regression, spatial_mean")
    period_start: datetime
    period_end: datetime
    input_dataset: str
    data_type: str = Field(..., description="observation | satellite_product | reanalysis | forecast | model")
    coverage: float = Field(..., description="Percentage of valid data points used (0.0 to 1.0)")
    source: str = Field(..., description="e.g., GEE, Open-Meteo, INCOIS")
    limitations: List[str] = Field(default=["Correlation does not establish causation."])

class ResearchObservation(BaseModel):
    """
    The normalized unit of scientific data. Providers must format raw data into this.
    """
    variable: str
    value: Optional[float]
    unit: str

    latitude: float
    longitude: float
    timestamp: datetime

    provider: str
    dataset: str
    data_type: str

    spatial_resolution: Optional[str] = None
    temporal_resolution: Optional[str] = None
    quality_flag: Optional[str] = None

class RegionSpec(BaseModel):
    name: str
    min_lat: float
    max_lat: float
    min_lon: float
    max_lon: float

class ResearchDataCube(BaseModel):
    """
    The canonical scientific data contract between providers, analysis engines, and agents.
    """
    region: RegionSpec
    start_time: datetime
    end_time: datetime
    variables: List[str]
    observations: List[ResearchObservation]
    provenance: List[DataProvenance] = []

class DatasetRecord(BaseModel):
    """
    Registry entry for a specific dataset, preventing LLM hallucinations.
    """
    dataset_id: str
    variable: str
    provider: str
    data_type: str
    temporal_coverage_start: datetime
    spatial_resolution: str
    temporal_resolution: str
    latency: str
    supported_operations: List[str]
    limitations: List[str]

class DataAcquisitionPlan(BaseModel):
    """
    The strict scientific plan generated by the Research Planner before fetching data.
    """
    objective: str
    region_name: str
    start_time: datetime
    end_time: datetime
    variables: List[Dict[str, Any]] # e.g., [{"name": "sst", "source_preference": ["satellite"]}]
    operations: List[str]
    research_context_required: bool = True
